---
sudo: required
services: docker
script: ./build
deploy:
  provider: script
  script: |
    curl -H "Content-Type: application/json" \
      --data '{"docker_tag": "dev"}' \
      -X POST https://registry.hub.docker.com/u/mtlynch/sia/trigger/4c446c18-9be1-4304-96ce-889126cccd84/
  on:
    branch: master
